Lab4 Front
daniildiveev/itmo-web pull request #5
Opened 2024-01-07 19:41 UTC by daniildiveev

Пока только фронт, бэк будет чуть позже

2024-01-07 20:11 UTC, danilkladnitsky requested changes

2024-01-07 20:11 UTC, danilkladnitsky commented on lab4/frontend/package.json
> +    "web-vitals": "^2.1.4"
`web-vitals` Вам незачем, плюс хорошая практика `"локать"` зависимости: можно убрать ^ со всех пакетов.

2024-01-07 20:11 UTC, danilkladnitsky commented on lab4/frontend/src/components/FormAndCanvas.jsx
> +    const currentRObject = useSelector(state => state.r) || {r: 1};
Лучше в стейте задать дефолтное значение для радиуса

2024-01-07 20:11 UTC, danilkladnitsky commented on lab4/frontend/src/components/FormAndCanvas.jsx
> +    const previousPointsObject = useSelector(state => state.points) || {points: []};
То же самое

2024-01-07 20:11 UTC, danilkladnitsky commented on lab4/frontend/src/components/Login.jsx
> +            const user = login(e.target.username.value, e.target.password.value);
```suggestion
            const { username: usernameField, password: passwordField } = e.target;
            const user = login(usernameField.value, passwordField.value);
```

2024-01-07 20:11 UTC, danilkladnitsky commented on lab4/frontend/src/components/Login.jsx
> +                    {PasswordInput()}
Надо вот так:
```<UsernameInput />```

2024-01-07 20:11 UTC, danilkladnitsky commented on lab4/frontend/src/components/Main.jsx
> +        );
Можно было бы и повыносить в компоненты
Тут шапка и футер явно просятся на отдельные файлы или хотя бы отдельные компоненты внутри Main.jsx

2024-01-07 20:11 UTC, danilkladnitsky commented on lab4/frontend/src/components/Main.jsx
> +                    </footer>
0_0 x2

2024-01-07 20:11 UTC, danilkladnitsky commented on lab4/frontend/src/components/Main.jsx
> +                </div>
0_0

2024-01-07 20:11 UTC, danilkladnitsky commented on lab4/frontend/src/reportWebVitals.js
> +export default reportWebVitals;
Вам это не нужно!

2024-01-07 20:11 UTC, danilkladnitsky commented on lab4/frontend/src/services/loginService.js
> +    console.log(username, password);
0_0

2024-01-07 20:11 UTC, danilkladnitsky commented on lab4/frontend/src/components/FormAndCanvas.jsx
> +export const FormAndCanvas = () => {
А лучше бы отдельно Form и отдельно Canvas

2024-01-07 20:13 UTC, danilkladnitsky commented on lab4/frontend/src/components/Login.jsx
> +            const user = login(e.target.username.value, e.target.password.value);
А вообще мы Реактовские так не работаем с инпутами. Мы назначаем обработчик onChange на компоненты вроде PasswordInput  и UsernameInput и сохраняем их значения в useState. И при вызове handleSubmit мы просто берем эти стейты и используем. Но я вам прощаю такое богохульство, потому что вы с МашинЛерновскими.

2024-01-07 20:22 UTC, daniildiveev commented on lab4/frontend/src/components/FormAndCanvas.jsx
> +export const FormAndCanvas = () => {
ответил в тг поэтому поводу

2024-01-08 00:30 UTC, daniildiveev commented
@danilkladnitsky 
фиксы по фронту готовы

2024-01-08 09:32 UTC, danilkladnitsky commented
> @danilkladnitsky фиксы по фронту готовы

Отлично.
Бэкенд готов?

2024-01-08 10:41 UTC, daniildiveev commented
бэк пока в работе, но до следующего допа успею точно, закидывать буду сюда же

2024-01-08 18:23 UTC, daniildiveev commented
@danilkladnitsky 

в целом бэк готов, осталось прикрутить к фронту, но было бы лучше, если бы вы просто на логику глянули сначала)

2024-01-09 14:45 UTC, danilkladnitsky approved these changes

2024-01-09 14:45 UTC, danilkladnitsky commented on lab4/backend/src/main/java/web/itmo/lab4/controller/HitController.java
> +    @PostMapping("/add")
Эндпоинт должен быть `POST /points`

2024-01-09 14:45 UTC, danilkladnitsky commented on lab4/backend/src/main/java/web/itmo/lab4/service/JWTService.java
> +    private static final String KEY = "399641f5bd69cd470e061d2d1bd6946c03855e89cfbff32f48f06eb5fd5876a4";
Это не надо коммитить

2024-01-09 15:04 UTC, daniildiveev commented on lab4/backend/src/main/java/web/itmo/lab4/service/JWTService.java
> +    private static final String KEY = "399641f5bd69cd470e061d2d1bd6946c03855e89cfbff32f48f06eb5fd5876a4";
тут понятно, лучше в какой-нибудь .env засунуть, я для простоты сразу в класс вбил

2024-01-09 15:04 UTC, daniildiveev commented on lab4/backend/src/main/java/web/itmo/lab4/controller/HitController.java
> +    @PostMapping("/add")
вот тут не очень понял

2024-01-09 18:25 UTC, daniildiveev commented
@danilkladnitsky привязал фронт к беку, гляньте, пожалуйста

2024-01-10 10:52 UTC, danilkladnitsky approved these changes

2024-01-10 10:52 UTC, danilkladnitsky commented on lab4/frontend/src/components/Login.jsx
> +            console.log("1")
0_0

2024-01-10 10:52 UTC, danilkladnitsky commented on lab4/frontend/src/services/loginService.js
> +        url = "http://localhost:8080/authentication/register";
`http://localhost:8080` -> API_HOST_URL

2024-01-10 10:52 UTC, danilkladnitsky commented on lab4/frontend/src/services/loginService.js
> +    }
```suggestion
    const body = { username, password }
```

2024-01-10 10:52 UTC, danilkladnitsky commented on lab4/frontend/src/services/loginService.js
> +    }
```
    const url = register ? "..." : "...";
```

2024-01-10 10:52 UTC, danilkladnitsky commented on lab4/frontend/src/services/loginService.js
> +    };
На всякий лучше обернуть в try, так как .json() может и сломаться

а потом можно просто
```
return responseData;
```

2024-01-10 10:52 UTC, danilkladnitsky commented on lab4/frontend/src/index.js
> +    </Provider>,
Провайдеры и PersistGate лучше в App вынести

```
function App() {
...
return (
<Provider store={store}>
    <PersistGate loading={null} persistor={persister}>
            ...
    </PersistGate>
</Provider>
)
}

2024-01-10 10:53 UTC, daniildiveev commented on lab4/frontend/src/components/Login.jsx
> +            console.log("1")
это дрилл дебаг)

2024-01-10 14:04 UTC, merged